config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get "/auth/:provider/callback" => "sessions#create"
  get '/auth/github' => "https://github.com/login/oauth/authorize?client_id=#{ENV["GITHUB_KEY"]}&scope=repo"

  root 'search#index'
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.access_token = auth["credentials"]["token"]
    end
  end

  def update_access_token(auth)
    self.access_token = auth["credentials"]["token"]
    self.save
    self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/search_controller.rb
require "github_search"
class SearchController < ApplicationController
  def index

    results_per_page = 20

    begin params[:search_term] 

      results = ::GithubSearch.search(params[:search_term], current_user.access_token, results_per_page, params[:page] || 1) if params[:search_term] && valid_access_token?

    rescue
      flash.now[:alert] = "Search can't be blank!"
    end

    @items = []
    @items = results["items"] if results

    total_pages = results["total_count"]/results_per_page if results
    total_pages += 1 if results && results['total_count']%results_per_page > 0

    total_count = 0
    total_count = results["total_count"] if results
    total_count = [total_count, 1000].min

    @items = Kaminari.paginate_array(@items, :total_count => total_count).page(params[:page]).per(results_per_page)
 
  end

  private
  
  def valid_access_token?
    begin
      RestClient.get "https://#{ENV['GITHUB_KEY']}:#{ENV['GITHUB_SECRET']}@api.github.com/applications/#{ENV['GITHUB_KEY']}/tokens/#{current_user.access_token}"
    rescue
      redirect_to '/auth/github'
      false
    else
      true
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def create
    auth = request.env["omniauth.auth"]
          #1: Check if user is in database
    user = if User.find_by_provider_and_uid(auth["provider"], auth["uid"])
            #2: Check if current_user is set
            if current_user
              #3: Check if access tokens match 
              if current_user.access_token == auth["credentials"]["token"]
                User.find_by_provider_and_uid(auth["provider"], auth["uid"])
              #3: else update them
              else
               current_user.update_access_token(auth)
              end
            #2: else set it
            else
              User.find_by_provider_and_uid(auth["provider"], auth["uid"])
            end
           #1: else create new user
           else
            User.create_with_omniauth(auth)
           end 
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/search/_result.html.erb
<tr>
<td><strong><%= link_to results["name"], results["html_url"] %></strong></td>
<td><%= results["owner"]["login"] %></td>
<td><%= results["stargazers_count"] %></td>
<td><%= results["forks_count"] %></td>
<td><%= results["open_issues_count"] %></td>
<td><%= results["language"] %></td>
<td><%= results["size"] %></td>
<td><%= results["updated_at"] %></td>
</tr>

app/views/search/index.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
      <li class="name">
        <h1><%= link_to("Search for Github Repositories", root_url) %></h1>
      </li>
    </ul>
    <% if current_user %>
      <%= form_tag search_index_path, :method => 'get' do %>   
        <ul class="right">
          <li class="has-form">
            <div class="row collapse">
              <div class="large-6 small-7 columns">
                <%= text_field_tag :search_term, params[:search_term] %>
              </div>
              <div class="large-3 small-2 columns left">
                <%= submit_tag "Search", class: "button"%>
              </div>
            </div>
          </li>
        </ul>
      <% end %>
    <% end %>
  </nav>
</div>

<div class="row">
  <div class="small3 small-centered text-center columns">
    <p id="alert">
     <font color="red"> <strong><%= alert %></strong></font>
    </p>
  </div>
</div>

<% unless current_user %>
  <p> 
    <div class="row">
      <div class="small-3 small-centered columns">
        <%= link_to "Github Authurization", "/auth/github", class: "small info button round" %>
      </div>
    </div>
  </p>
<% end %>

<% if current_user %>
  <p>
    <div class="row collapse">
      <div class="small-8 small-centered columns text-center">
        <ul class="pagination">
        <%= paginate @items %>
        </ul>
      </div>
      <table>
        <thead>
          <th width="150">Repo Name</th>
          <th width="125">Author</th>
          <th>Stars</th>
          <th>Forks</th>
          <th>Open Issues</th>
          <th>Language</th>
          <th>Line Count</th>
          <th>Last Updated</th>
        </thead>
        <tbody>
          <% @items.each do |results| %>
            <%= render 'result', :results => results %>
          <% end %>
        </tbody>
      </table>
      <div class="small-8 small-centered columns text-center">
        <%= paginate @items %>
      </div>      
    </div>
  </p>
<% end %>

app/views/search/results.html.erb
<h1>Results</h1>